### ISSUE TITLE
Error in API

### ISSUE THREAD

**Issue by daredevil12345** [decoxviii/karma#5]
> Searching
Error: SOCKSHTTPConnectionPool(host='pwndb2am4tzkvold.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7f0bf2db47b8>: Failed to establish a new connection: [Errno 111] Connection refused',))

Can you explain its solution. 

best 
a newbie

**Comment by decoxviii** [comment]
Hi @daredevil12345 

**Karma** requires that the Tor service be active. Otherwise the port that Tor uses (default: 9050) will not be active and will get that error.

To solve the error:

1. Open terminal
2. Run command: `$ sudo service tor restart` (This restarts the tor service)
3. Try a search with karma `$  python3 bin/karma.py search 123456 --password`

**Comment by smetal1** [comment]
[x] SOCKSHTTPConnectionPool(host='pwndb2am4tzkvold.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x10871d410>: Failed to establish a new connection: [Errno 61] Connection refused'))
